name: Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  schedule:
    # Amsterdam time (CET) is UTC+1, so schedule for 9pm UTC
    - cron: '0 21 * * *'  # Every day at 9:00 PM UTC (10:00 PM CET)
    
permissions:
  contents: read

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        ls -la
        python -m pip install --upgrade pip
        pip install -r ./converter/publisher/requirements.txt

    - name: Publish MD files to the Confluence space
      env:
        LOGIN: ${{ secrets.confluence_login }}
        PASSWORD: ${{ secrets.confluence_password }}
      run: |
        python3 ./converter/publisher/main.py --login="$LOGIN" --password="$PASSWORD"
